name: Create CHANGELOG PR

on:
  push:
    branches:
      - stable
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Detect version change
        id: check
        run: |
          if git diff HEAD^ HEAD --name-only | grep -q "_version.py"; then
            echo "release=true" >> $GITHUB_OUTPUT
          else
            echo "release=false" >> $GITHUB_OUTPUT
          fi

      - name: Stop if not release
        if: steps.check.outputs.release != 'true'
        run: exit 0

      - name: Extract version
        id: get_version
        run: |
          VERSION=$(sed -n 's/^__version__[[:space:]]*=[[:space:]]*"\(.*\)"/\1/p' rplibs/_version.py)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Update CHANGELOG.md
        run: |
          DATE=$(date +'%Y-%m-%d')
          VERSION=${{ steps.get_version.outputs.version }}
          echo -e "## [$VERSION] - $DATE\n\n- Release $VERSION\n\n$(cat CHANGELOG.md)" > CHANGELOG.md

      - name: Create PR for changelog
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: release/${{ steps.get_version.outputs.version }}
          base: stable
          title: "Release ${{ steps.get_version.outputs.version }}"
          commit-message: "chore(release): update CHANGELOG"

      - name: Enable auto-merge
        if: steps.cpr.outputs.pull-request-number != ''
        run: |
            gh pr merge ${{ steps.cpr.outputs.pull-request-number }} --auto --merge
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
